import { WhiteboardElement, WhiteboardBoard } from '../types/whiteboard';

export interface BoardTemplate {
  id: string;
  name: string;
  description: string;
  iconName: string;
  category: 'general' | 'education' | 'engineering' | 'planning';
  createBoard: () => WhiteboardBoard;
}

export const WHITEBOARD_TEMPLATES: BoardTemplate[] = [
  {
    id: 'blank',
    name: 'Blank Board',
    description: 'Clean slate with infinite canvas and distraction-free workspace.',
    iconName: 'Square',
    category: 'general',
    createBoard: () => {
      const now = Date.now();
      return {
        id: `board_${now}`,
        title: 'Untitled Whiteboard',
        createdAt: now,
        updatedAt: now,
        backgroundColor: '#0f172a',
        gridType: 'none',
        gridSnap: false,
        viewport: { x: 0, y: 0, zoom: 1 },
        elements: [],
        frames: [],
      };
    },
  },

  {
    id: 'class-notes',
    name: 'Class & Lecture Notes',
    description: 'Structured layout for online teaching with topic frames, formula card, and sticky questions.',
    iconName: 'BookOpen',
    category: 'education',
    createBoard: () => {
      const now = Date.now();
      const elements: WhiteboardElement[] = [
        {
          id: `el_frame_${now}_1`,
          type: 'frame',
          x: 100,
          y: 80,
          width: 900,
          height: 600,
          strokeColor: '#6366f1',
          strokeWidth: 2,
          fillColor: 'transparent',
          opacity: 1,
          zIndex: 0,
          frameTitle: 'Lecture 1: Core Principles',
        },
        {
          id: `el_txt_${now}_1`,
          type: 'text',
          x: 140,
          y: 120,
          width: 500,
          height: 40,
          strokeColor: '#f8fafc',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 1,
          text: 'Topic Overview & Objectives',
          fontSize: 28,
          bold: true,
        },
        {
          id: `el_txt_${now}_2`,
          type: 'text',
          x: 140,
          y: 180,
          width: 450,
          height: 120,
          strokeColor: '#94a3b8',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 2,
          text: '1. Understand the fundamental laws of motion\n2. Calculate velocity, acceleration, and momentum\n3. Real-world vector physics examples',
          fontSize: 16,
        },
        {
          id: `el_sticky_${now}_1`,
          type: 'sticky',
          x: 650,
          y: 150,
          width: 220,
          height: 200,
          strokeColor: '#ca8a04',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 3,
          stickyColor: '#fef08a',
          text: '💡 Key Formula:\n\nF = m · a\n\np = m · v\n\nRemember SI units:\nForce in Newtons (N)',
        },
        {
          id: `el_rect_${now}_1`,
          type: 'rounded_rectangle',
          x: 140,
          y: 340,
          width: 380,
          height: 180,
          strokeColor: '#38bdf8',
          strokeWidth: 2,
          fillColor: 'rgba(56, 189, 248, 0.08)',
          opacity: 1,
          zIndex: 4,
        },
        {
          id: `el_txt_${now}_3`,
          type: 'text',
          x: 160,
          y: 360,
          width: 340,
          height: 30,
          strokeColor: '#38bdf8',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 5,
          text: 'Worked Example Problem',
          fontSize: 18,
          bold: true,
        },
        {
          id: `el_txt_${now}_4`,
          type: 'text',
          x: 160,
          y: 400,
          width: 340,
          height: 100,
          strokeColor: '#cbd5e1',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 6,
          text: 'A 1,200 kg vehicle accelerates from rest to 25 m/s in 8.0 s.\nCalculate the net force applied.',
          fontSize: 15,
        },
      ];

      return {
        id: `board_${now}`,
        title: 'Physics Lecture Notes',
        createdAt: now,
        updatedAt: now,
        backgroundColor: '#0f172a',
        gridType: 'ruled',
        gridSnap: false,
        viewport: { x: 0, y: 0, zoom: 1 },
        elements,
        frames: [{ id: `frame_${now}_1`, title: 'Lecture 1: Core Principles', elementId: `el_frame_${now}_1` }],
      };
    },
  },

  {
    id: 'flowchart',
    name: 'Flowchart & Process',
    description: 'Connected flowchart process with start, action steps, decision diamonds, and connectors.',
    iconName: 'GitFork',
    category: 'engineering',
    createBoard: () => {
      const now = Date.now();
      const elStart = `el_start_${now}`;
      const elProcess = `el_proc_${now}`;
      const elDecision = `el_dec_${now}`;
      const elSuccess = `el_succ_${now}`;
      const elRetry = `el_retry_${now}`;

      const elements: WhiteboardElement[] = [
        // Start Pill
        {
          id: elStart,
          type: 'rounded_rectangle',
          x: 400,
          y: 100,
          width: 180,
          height: 60,
          strokeColor: '#10b981',
          strokeWidth: 2,
          fillColor: 'rgba(16, 185, 129, 0.15)',
          opacity: 1,
          zIndex: 1,
        },
        {
          id: `txt_${elStart}`,
          type: 'text',
          x: 440,
          y: 118,
          width: 100,
          height: 24,
          strokeColor: '#ffffff',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 2,
          text: 'Start Process',
          fontSize: 16,
          bold: true,
          textAlign: 'center',
        },

        // Process Step
        {
          id: elProcess,
          type: 'rectangle',
          x: 400,
          y: 220,
          width: 180,
          height: 70,
          strokeColor: '#38bdf8',
          strokeWidth: 2,
          fillColor: 'rgba(56, 189, 248, 0.15)',
          opacity: 1,
          zIndex: 3,
        },
        {
          id: `txt_${elProcess}`,
          type: 'text',
          x: 410,
          y: 242,
          width: 160,
          height: 24,
          strokeColor: '#ffffff',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 4,
          text: 'Validate Document',
          fontSize: 15,
          bold: true,
          textAlign: 'center',
        },

        // Decision Diamond
        {
          id: elDecision,
          type: 'diamond',
          x: 390,
          y: 350,
          width: 200,
          height: 100,
          strokeColor: '#f59e0b',
          strokeWidth: 2,
          fillColor: 'rgba(245, 158, 11, 0.15)',
          opacity: 1,
          zIndex: 5,
        },
        {
          id: `txt_${elDecision}`,
          type: 'text',
          x: 430,
          y: 388,
          width: 120,
          height: 24,
          strokeColor: '#ffffff',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 6,
          text: 'Format Valid?',
          fontSize: 15,
          bold: true,
          textAlign: 'center',
        },

        // Success End
        {
          id: elSuccess,
          type: 'rounded_rectangle',
          x: 400,
          y: 520,
          width: 180,
          height: 60,
          strokeColor: '#8b5cf6',
          strokeWidth: 2,
          fillColor: 'rgba(139, 92, 246, 0.15)',
          opacity: 1,
          zIndex: 7,
        },
        {
          id: `txt_${elSuccess}`,
          type: 'text',
          x: 430,
          y: 538,
          width: 120,
          height: 24,
          strokeColor: '#ffffff',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 8,
          text: 'Export Output',
          fontSize: 16,
          bold: true,
          textAlign: 'center',
        },

        // Retry Action
        {
          id: elRetry,
          type: 'rectangle',
          x: 680,
          y: 365,
          width: 160,
          height: 70,
          strokeColor: '#ef4444',
          strokeWidth: 2,
          fillColor: 'rgba(239, 68, 68, 0.15)',
          opacity: 1,
          zIndex: 9,
        },
        {
          id: `txt_${elRetry}`,
          type: 'text',
          x: 690,
          y: 388,
          width: 140,
          height: 24,
          strokeColor: '#ffffff',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 10,
          text: 'Show Error Modal',
          fontSize: 15,
          bold: true,
          textAlign: 'center',
        },

        // Connectors
        {
          id: `conn_${now}_1`,
          type: 'connector',
          x: 490,
          y: 160,
          width: 0,
          height: 60,
          strokeColor: '#10b981',
          strokeWidth: 2,
          opacity: 1,
          zIndex: 11,
          connectorType: 'straight',
          connectorStart: { elementId: elStart, anchor: 'bottom', x: 490, y: 160 },
          connectorEnd: { elementId: elProcess, anchor: 'top', x: 490, y: 220 },
        },
        {
          id: `conn_${now}_2`,
          type: 'connector',
          x: 490,
          y: 290,
          width: 0,
          height: 60,
          strokeColor: '#38bdf8',
          strokeWidth: 2,
          opacity: 1,
          zIndex: 12,
          connectorType: 'straight',
          connectorStart: { elementId: elProcess, anchor: 'bottom', x: 490, y: 290 },
          connectorEnd: { elementId: elDecision, anchor: 'top', x: 490, y: 350 },
        },
        {
          id: `conn_${now}_3`,
          type: 'connector',
          x: 490,
          y: 450,
          width: 0,
          height: 70,
          strokeColor: '#10b981',
          strokeWidth: 2,
          opacity: 1,
          zIndex: 13,
          connectorType: 'straight',
          connectorStart: { elementId: elDecision, anchor: 'bottom', x: 490, y: 450 },
          connectorEnd: { elementId: elSuccess, anchor: 'top', x: 490, y: 520 },
        },
        {
          id: `conn_${now}_4`,
          type: 'connector',
          x: 590,
          y: 400,
          width: 90,
          height: 0,
          strokeColor: '#ef4444',
          strokeWidth: 2,
          opacity: 1,
          zIndex: 14,
          connectorType: 'straight',
          connectorStart: { elementId: elDecision, anchor: 'right', x: 590, y: 400 },
          connectorEnd: { elementId: elRetry, anchor: 'left', x: 680, y: 400 },
        },
      ];

      return {
        id: `board_${now}`,
        title: 'Document Flowchart',
        createdAt: now,
        updatedAt: now,
        backgroundColor: '#0f172a',
        gridType: 'square',
        gridSnap: true,
        viewport: { x: 0, y: 0, zoom: 1 },
        elements,
        frames: [],
      };
    },
  },

  {
    id: 'mind-map',
    name: 'Mind Map',
    description: 'Central concept with radiating curved connectors and colorful idea nodes.',
    iconName: 'Network',
    category: 'planning',
    createBoard: () => {
      const now = Date.now();
      const elCenter = `el_center_${now}`;

      const elements: WhiteboardElement[] = [
        // Central Node
        {
          id: elCenter,
          type: 'circle',
          x: 450,
          y: 300,
          width: 180,
          height: 120,
          strokeColor: '#6366f1',
          strokeWidth: 3,
          fillColor: 'rgba(99, 102, 241, 0.25)',
          opacity: 1,
          zIndex: 1,
        },
        {
          id: `txt_${elCenter}`,
          type: 'text',
          x: 480,
          y: 345,
          width: 120,
          height: 30,
          strokeColor: '#ffffff',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 2,
          text: 'Core Strategy',
          fontSize: 18,
          bold: true,
          textAlign: 'center',
        },

        // North Branch
        {
          id: `el_north_${now}`,
          type: 'rounded_rectangle',
          x: 450,
          y: 100,
          width: 180,
          height: 60,
          strokeColor: '#10b981',
          strokeWidth: 2,
          fillColor: 'rgba(16, 185, 129, 0.15)',
          opacity: 1,
          zIndex: 3,
        },
        {
          id: `txt_north_${now}`,
          type: 'text',
          x: 470,
          y: 118,
          width: 140,
          height: 24,
          strokeColor: '#34d399',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 4,
          text: 'User Experience',
          fontSize: 16,
          bold: true,
          textAlign: 'center',
        },

        // East Branch
        {
          id: `el_east_${now}`,
          type: 'rounded_rectangle',
          x: 750,
          y: 330,
          width: 180,
          height: 60,
          strokeColor: '#f59e0b',
          strokeWidth: 2,
          fillColor: 'rgba(245, 158, 11, 0.15)',
          opacity: 1,
          zIndex: 5,
        },
        {
          id: `txt_east_${now}`,
          type: 'text',
          x: 770,
          y: 348,
          width: 140,
          height: 24,
          strokeColor: '#fbbf24',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 6,
          text: 'Performance',
          fontSize: 16,
          bold: true,
          textAlign: 'center',
        },

        // South Branch
        {
          id: `el_south_${now}`,
          type: 'rounded_rectangle',
          x: 450,
          y: 530,
          width: 180,
          height: 60,
          strokeColor: '#ec4899',
          strokeWidth: 2,
          fillColor: 'rgba(236, 72, 153, 0.15)',
          opacity: 1,
          zIndex: 7,
        },
        {
          id: `txt_south_${now}`,
          type: 'text',
          x: 470,
          y: 548,
          width: 140,
          height: 24,
          strokeColor: '#f472b6',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 8,
          text: 'Privacy & Security',
          fontSize: 16,
          bold: true,
          textAlign: 'center',
        },

        // West Branch
        {
          id: `el_west_${now}`,
          type: 'rounded_rectangle',
          x: 150,
          y: 330,
          width: 180,
          height: 60,
          strokeColor: '#06b6d4',
          strokeWidth: 2,
          fillColor: 'rgba(6, 182, 212, 0.15)',
          opacity: 1,
          zIndex: 9,
        },
        {
          id: `txt_west_${now}`,
          type: 'text',
          x: 170,
          y: 348,
          width: 140,
          height: 24,
          strokeColor: '#22d3ee',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 10,
          text: 'SEO & Growth',
          fontSize: 16,
          bold: true,
          textAlign: 'center',
        },

        // Curved Connectors
        {
          id: `conn_${now}_n`,
          type: 'connector',
          x: 540,
          y: 300,
          width: 0,
          height: -140,
          strokeColor: '#10b981',
          strokeWidth: 2.5,
          opacity: 1,
          zIndex: 11,
          connectorType: 'curved',
          connectorStart: { elementId: elCenter, anchor: 'top', x: 540, y: 300 },
          connectorEnd: { elementId: `el_north_${now}`, anchor: 'bottom', x: 540, y: 160 },
        },
        {
          id: `conn_${now}_e`,
          type: 'connector',
          x: 630,
          y: 360,
          width: 120,
          height: 0,
          strokeColor: '#f59e0b',
          strokeWidth: 2.5,
          opacity: 1,
          zIndex: 12,
          connectorType: 'curved',
          connectorStart: { elementId: elCenter, anchor: 'right', x: 630, y: 360 },
          connectorEnd: { elementId: `el_east_${now}`, anchor: 'left', x: 750, y: 360 },
        },
        {
          id: `conn_${now}_s`,
          type: 'connector',
          x: 540,
          y: 420,
          width: 0,
          height: 110,
          strokeColor: '#ec4899',
          strokeWidth: 2.5,
          opacity: 1,
          zIndex: 13,
          connectorType: 'curved',
          connectorStart: { elementId: elCenter, anchor: 'bottom', x: 540, y: 420 },
          connectorEnd: { elementId: `el_south_${now}`, anchor: 'top', x: 540, y: 530 },
        },
        {
          id: `conn_${now}_w`,
          type: 'connector',
          x: 450,
          y: 360,
          width: -120,
          height: 0,
          strokeColor: '#06b6d4',
          strokeWidth: 2.5,
          opacity: 1,
          zIndex: 14,
          connectorType: 'curved',
          connectorStart: { elementId: elCenter, anchor: 'left', x: 450, y: 360 },
          connectorEnd: { elementId: `el_west_${now}`, anchor: 'right', x: 330, y: 360 },
        },
      ];

      return {
        id: `board_${now}`,
        title: 'Mind Map Diagram',
        createdAt: now,
        updatedAt: now,
        backgroundColor: '#0f172a',
        gridType: 'dot',
        gridSnap: false,
        viewport: { x: 0, y: 0, zoom: 1 },
        elements,
        frames: [],
      };
    },
  },

  {
    id: 'brainstorming',
    name: 'Brainstorming & Kanban',
    description: 'Sticky notes board organized into columns: Ideas, In Progress, and Implemented.',
    iconName: 'StickyNote',
    category: 'planning',
    createBoard: () => {
      const now = Date.now();
      const elements: WhiteboardElement[] = [
        // Column 1: Ideas
        {
          id: `col_frame_1`,
          type: 'frame',
          x: 80,
          y: 80,
          width: 320,
          height: 650,
          strokeColor: '#38bdf8',
          strokeWidth: 2,
          fillColor: 'transparent',
          opacity: 1,
          zIndex: 0,
          frameTitle: '💡 New Ideas',
        },
        {
          id: `sticky_1`,
          type: 'sticky',
          x: 120,
          y: 140,
          width: 240,
          height: 150,
          strokeColor: '#ca8a04',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 1,
          stickyColor: '#fef08a',
          text: 'Add audio waveform visualizer for speech notes.',
        },
        {
          id: `sticky_2`,
          type: 'sticky',
          x: 120,
          y: 320,
          width: 240,
          height: 150,
          strokeColor: '#0284c7',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 2,
          stickyColor: '#bae6fd',
          text: 'Support Apple Pencil tilt and pressure shading.',
        },

        // Column 2: In Progress
        {
          id: `col_frame_2`,
          type: 'frame',
          x: 440,
          y: 80,
          width: 320,
          height: 650,
          strokeColor: '#f59e0b',
          strokeWidth: 2,
          fillColor: 'transparent',
          opacity: 1,
          zIndex: 0,
          frameTitle: '⏳ In Progress',
        },
        {
          id: `sticky_3`,
          type: 'sticky',
          x: 480,
          y: 140,
          width: 240,
          height: 150,
          strokeColor: '#ea580c',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 3,
          stickyColor: '#fed7aa',
          text: 'Export vector SVG format with high fidelity.',
        },
        {
          id: `sticky_4`,
          type: 'sticky',
          x: 480,
          y: 320,
          width: 240,
          height: 150,
          strokeColor: '#ca8a04',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 4,
          stickyColor: '#fef08a',
          text: 'Multi-select alignment and horizontal distribution.',
        },

        // Column 3: Done
        {
          id: `col_frame_3`,
          type: 'frame',
          x: 800,
          y: 80,
          width: 320,
          height: 650,
          strokeColor: '#10b981',
          strokeWidth: 2,
          fillColor: 'transparent',
          opacity: 1,
          zIndex: 0,
          frameTitle: '✅ Implemented',
        },
        {
          id: `sticky_5`,
          type: 'sticky',
          x: 840,
          y: 140,
          width: 240,
          height: 150,
          strokeColor: '#15803d',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 5,
          stickyColor: '#bbf7d0',
          text: 'High-res image paste from clipboard with alpha channel.',
        },
      ];

      return {
        id: `board_${now}`,
        title: 'Sprint Brainstorming Board',
        createdAt: now,
        updatedAt: now,
        backgroundColor: '#0f172a',
        gridType: 'none',
        gridSnap: false,
        viewport: { x: 0, y: 0, zoom: 1 },
        elements,
        frames: [
          { id: 'f1', title: '💡 New Ideas', elementId: 'col_frame_1' },
          { id: 'f2', title: '⏳ In Progress', elementId: 'col_frame_2' },
          { id: 'f3', title: '✅ Implemented', elementId: 'col_frame_3' },
        ],
      };
    },
  },

  {
    id: 'kanban-board',
    name: 'Agile Kanban Sprint',
    description: '3-stage visual delivery board: To Do, In Progress, and Completed stories with priority sticky cards.',
    iconName: 'LayoutGrid',
    category: 'planning',
    createBoard: () => {
      const now = Date.now();
      const elements: WhiteboardElement[] = [
        // Column 1: Backlog / To Do
        {
          id: `kanban_col_1_${now}`,
          type: 'frame',
          x: 80,
          y: 60,
          width: 320,
          height: 640,
          strokeColor: '#64748b',
          strokeWidth: 2,
          fillColor: 'rgba(30, 41, 59, 0.4)',
          opacity: 1,
          zIndex: 1,
          frameTitle: '📋 TO DO (Backlog)',
        },
        {
          id: `kanban_card_1_${now}`,
          type: 'sticky',
          x: 105,
          y: 110,
          width: 270,
          height: 120,
          strokeColor: '#f59e0b',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 2,
          stickyColor: '#fef3c7',
          text: '⚡ High Priority: Optimize image upload & multi-threaded compression',
        },
        {
          id: `kanban_card_2_${now}`,
          type: 'sticky',
          x: 105,
          y: 250,
          width: 270,
          height: 110,
          strokeColor: '#38bdf8',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 3,
          stickyColor: '#e0f2fe',
          text: '📝 Add dark mode SVG export support with crisp typography',
        },

        // Column 2: In Progress
        {
          id: `kanban_col_2_${now}`,
          type: 'frame',
          x: 430,
          y: 60,
          width: 320,
          height: 640,
          strokeColor: '#3b82f6',
          strokeWidth: 2,
          fillColor: 'rgba(30, 41, 59, 0.4)',
          opacity: 1,
          zIndex: 1,
          frameTitle: '🚀 IN PROGRESS',
        },
        {
          id: `kanban_card_3_${now}`,
          type: 'sticky',
          x: 455,
          y: 110,
          width: 270,
          height: 120,
          strokeColor: '#6366f1',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 4,
          stickyColor: '#ede9fe',
          text: '🎨 Freehand Catmull-Rom spline curves & low-latency drawing engine',
        },
        {
          id: `kanban_card_4_${now}`,
          type: 'sticky',
          x: 455,
          y: 250,
          width: 270,
          height: 110,
          strokeColor: '#ec4899',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 5,
          stickyColor: '#fce7f3',
          text: '📋 Clipboard image direct paste (Ctrl+V) handler',
        },

        // Column 3: Done
        {
          id: `kanban_col_3_${now}`,
          type: 'frame',
          x: 780,
          y: 60,
          width: 320,
          height: 640,
          strokeColor: '#10b981',
          strokeWidth: 2,
          fillColor: 'rgba(30, 41, 59, 0.4)',
          opacity: 1,
          zIndex: 1,
          frameTitle: '✅ COMPLETED',
        },
        {
          id: `kanban_card_5_${now}`,
          type: 'sticky',
          x: 805,
          y: 110,
          width: 270,
          height: 110,
          strokeColor: '#10b981',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 6,
          stickyColor: '#d1fae5',
          text: '✨ Fullscreen immersive canvas layout with Back to ToolTrack',
        },
        {
          id: `kanban_card_6_${now}`,
          type: 'sticky',
          x: 805,
          y: 240,
          width: 270,
          height: 110,
          strokeColor: '#10b981',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 7,
          stickyColor: '#d1fae5',
          text: '🔒 Auto-selection bug eliminated: drawings stay natural by default',
        },
      ];

      return {
        id: `board_${now}`,
        title: 'Sprint Kanban Board',
        createdAt: now,
        updatedAt: now,
        backgroundColor: '#0f172a',
        gridType: 'none',
        gridSnap: false,
        viewport: { x: 0, y: 0, zoom: 1 },
        elements,
        frames: [
          { id: 'kb1', title: '📋 TO DO (Backlog)', elementId: `kanban_col_1_${now}` },
          { id: 'kb2', title: '🚀 IN PROGRESS', elementId: `kanban_col_2_${now}` },
          { id: 'kb3', title: '✅ COMPLETED', elementId: `kanban_col_3_${now}` },
        ],
      };
    },
  },

  {
    id: 'system-architecture',
    name: 'Cloud System Architecture',
    description: 'End-to-end architecture diagram: Clients, API Gateway, Services, Database, and Cache with directional flows.',
    iconName: 'Server',
    category: 'engineering',
    createBoard: () => {
      const now = Date.now();
      const elements: WhiteboardElement[] = [
        // Title Frame
        {
          id: `arch_title_${now}`,
          type: 'text',
          x: 80,
          y: 60,
          width: 480,
          height: 40,
          strokeColor: '#f8fafc',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 1,
          text: 'Microservices Cloud Architecture',
          fontSize: 26,
          bold: true,
        },
        // Client Tier
        {
          id: `arch_client_${now}`,
          type: 'rounded_rectangle',
          x: 80,
          y: 180,
          width: 170,
          height: 90,
          strokeColor: '#38bdf8',
          strokeWidth: 2,
          fillColor: 'rgba(56, 189, 248, 0.12)',
          opacity: 1,
          zIndex: 2,
        },
        {
          id: `arch_client_txt_${now}`,
          type: 'text',
          x: 95,
          y: 205,
          width: 140,
          height: 40,
          strokeColor: '#ffffff',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 3,
          text: 'Web & Mobile Client\n(React SPA / iOS)',
          fontSize: 14,
          textAlign: 'center',
          bold: true,
        },
        // API Gateway
        {
          id: `arch_gw_${now}`,
          type: 'rounded_rectangle',
          x: 340,
          y: 180,
          width: 180,
          height: 90,
          strokeColor: '#6366f1',
          strokeWidth: 2,
          fillColor: 'rgba(99, 102, 241, 0.14)',
          opacity: 1,
          zIndex: 2,
        },
        {
          id: `arch_gw_txt_${now}`,
          type: 'text',
          x: 355,
          y: 205,
          width: 150,
          height: 40,
          strokeColor: '#ffffff',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 3,
          text: 'API Gateway\n(Rate Limit & Auth)',
          fontSize: 14,
          textAlign: 'center',
          bold: true,
        },
        // Arrow 1: Client -> Gateway
        {
          id: `arch_arr1_${now}`,
          type: 'arrow',
          x: 250,
          y: 225,
          width: 90,
          height: 0,
          strokeColor: '#38bdf8',
          strokeWidth: 2,
          opacity: 1,
          zIndex: 4,
        },
        // Service A
        {
          id: `arch_svca_${now}`,
          type: 'rectangle',
          x: 610,
          y: 110,
          width: 180,
          height: 80,
          strokeColor: '#10b981',
          strokeWidth: 2,
          fillColor: 'rgba(16, 185, 129, 0.12)',
          opacity: 1,
          zIndex: 2,
        },
        {
          id: `arch_svca_txt_${now}`,
          type: 'text',
          x: 625,
          y: 130,
          width: 150,
          height: 40,
          strokeColor: '#ffffff',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 3,
          text: 'Auth Service\n(OAuth / JWT)',
          fontSize: 14,
          textAlign: 'center',
          bold: true,
        },
        // Service B
        {
          id: `arch_svcb_${now}`,
          type: 'rectangle',
          x: 610,
          y: 250,
          width: 180,
          height: 80,
          strokeColor: '#f59e0b',
          strokeWidth: 2,
          fillColor: 'rgba(245, 158, 11, 0.12)',
          opacity: 1,
          zIndex: 2,
        },
        {
          id: `arch_svcb_txt_${now}`,
          type: 'text',
          x: 625,
          y: 270,
          width: 150,
          height: 40,
          strokeColor: '#ffffff',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 3,
          text: 'Document Engine\n(PDF / Image Ops)',
          fontSize: 14,
          textAlign: 'center',
          bold: true,
        },
        // Database
        {
          id: `arch_db_${now}`,
          type: 'diamond',
          x: 880,
          y: 170,
          width: 180,
          height: 110,
          strokeColor: '#ec4899',
          strokeWidth: 2,
          fillColor: 'rgba(236, 72, 153, 0.12)',
          opacity: 1,
          zIndex: 2,
        },
        {
          id: `arch_db_txt_${now}`,
          type: 'text',
          x: 900,
          y: 215,
          width: 140,
          height: 24,
          strokeColor: '#ffffff',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 3,
          text: 'PostgreSQL DB',
          fontSize: 14,
          textAlign: 'center',
          bold: true,
        },
      ];

      return {
        id: `board_${now}`,
        title: 'System Architecture Diagram',
        createdAt: now,
        updatedAt: now,
        backgroundColor: '#0f172a',
        gridType: 'none',
        gridSnap: false,
        viewport: { x: 0, y: 0, zoom: 1 },
        elements,
        frames: [],
      };
    },
  },

  {
    id: 'sprint-retro',
    name: 'Sprint Retrospective (4L)',
    description: 'Team retrospective matrix: What Went Well, What Didn’t, New Ideas, and Action Items.',
    iconName: 'MessageSquare',
    category: 'planning',
    createBoard: () => {
      const now = Date.now();
      const elements: WhiteboardElement[] = [
        // Quadrant 1: Went Well (Green)
        {
          id: `retro_q1_${now}`,
          type: 'frame',
          x: 80,
          y: 80,
          width: 440,
          height: 320,
          strokeColor: '#10b981',
          strokeWidth: 2,
          fillColor: 'rgba(16, 185, 129, 0.08)',
          opacity: 1,
          zIndex: 1,
          frameTitle: '🌟 What Went Well',
        },
        {
          id: `retro_note1_${now}`,
          type: 'sticky',
          x: 110,
          y: 130,
          width: 180,
          height: 120,
          strokeColor: '#10b981',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 2,
          stickyColor: '#d1fae5',
          text: 'Great teamwork delivering whiteboard drawing performance!',
        },
        {
          id: `retro_note2_${now}`,
          type: 'sticky',
          x: 310,
          y: 130,
          width: 180,
          height: 120,
          strokeColor: '#10b981',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 3,
          stickyColor: '#d1fae5',
          text: 'Clean fullscreen UI without header distractions',
        },

        // Quadrant 2: Didn't Go Well (Rose)
        {
          id: `retro_q2_${now}`,
          type: 'frame',
          x: 560,
          y: 80,
          width: 440,
          height: 320,
          strokeColor: '#f43f5e',
          strokeWidth: 2,
          fillColor: 'rgba(244, 63, 94, 0.08)',
          opacity: 1,
          zIndex: 1,
          frameTitle: '⚠️ What Needs Improvement',
        },
        {
          id: `retro_note3_${now}`,
          type: 'sticky',
          x: 590,
          y: 130,
          width: 180,
          height: 120,
          strokeColor: '#f43f5e',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 4,
          stickyColor: '#ffe4e6',
          text: 'Flaky clipboard events on older Safari versions',
        },

        // Quadrant 3: Ideas (Amber)
        {
          id: `retro_q3_${now}`,
          type: 'frame',
          x: 80,
          y: 440,
          width: 440,
          height: 320,
          strokeColor: '#f59e0b',
          strokeWidth: 2,
          fillColor: 'rgba(245, 158, 11, 0.08)',
          opacity: 1,
          zIndex: 1,
          frameTitle: '💡 Ideas & Experiments',
        },
        {
          id: `retro_note4_${now}`,
          type: 'sticky',
          x: 110,
          y: 490,
          width: 180,
          height: 120,
          strokeColor: '#f59e0b',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 5,
          stickyColor: '#fef3c7',
          text: 'Add quick handwriting math equation recognition',
        },

        // Quadrant 4: Action Items (Indigo)
        {
          id: `retro_q4_${now}`,
          type: 'frame',
          x: 560,
          y: 440,
          width: 440,
          height: 320,
          strokeColor: '#6366f1',
          strokeWidth: 2,
          fillColor: 'rgba(99, 102, 241, 0.08)',
          opacity: 1,
          zIndex: 1,
          frameTitle: '🎯 Action Items & Owners',
        },
        {
          id: `retro_note5_${now}`,
          type: 'sticky',
          x: 590,
          y: 490,
          width: 180,
          height: 120,
          strokeColor: '#6366f1',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 6,
          stickyColor: '#ede9fe',
          text: 'Release v2.0 Whiteboard with direct paste & smooth curves',
        },
      ];

      return {
        id: `board_${now}`,
        title: 'Sprint Retrospective',
        createdAt: now,
        updatedAt: now,
        backgroundColor: '#0f172a',
        gridType: 'none',
        gridSnap: false,
        viewport: { x: 0, y: 0, zoom: 1 },
        elements,
        frames: [
          { id: 'rq1', title: '🌟 What Went Well', elementId: `retro_q1_${now}` },
          { id: 'rq2', title: '⚠️ What Needs Improvement', elementId: `retro_q2_${now}` },
          { id: 'rq3', title: '💡 Ideas & Experiments', elementId: `retro_q3_${now}` },
          { id: 'rq4', title: '🎯 Action Items & Owners', elementId: `retro_q4_${now}` },
        ],
      };
    },
  },

  {
    id: 'swot-analysis',
    name: 'Strategic SWOT Analysis',
    description: '2x2 Strategic planning matrix: Strengths, Weaknesses, Opportunities, and Threats.',
    iconName: 'Target',
    category: 'planning',
    createBoard: () => {
      const now = Date.now();
      const elements: WhiteboardElement[] = [
        // Strengths
        {
          id: `swot_s_${now}`,
          type: 'rounded_rectangle',
          x: 80,
          y: 80,
          width: 440,
          height: 300,
          strokeColor: '#10b981',
          strokeWidth: 2,
          fillColor: 'rgba(16, 185, 129, 0.08)',
          opacity: 1,
          zIndex: 1,
        },
        {
          id: `swot_s_txt_${now}`,
          type: 'text',
          x: 105,
          y: 100,
          width: 200,
          height: 30,
          strokeColor: '#10b981',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 2,
          text: 'STRENGTHS',
          fontSize: 18,
          bold: true,
        },
        {
          id: `swot_s_note_${now}`,
          type: 'sticky',
          x: 110,
          y: 150,
          width: 200,
          height: 120,
          strokeColor: '#10b981',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 3,
          stickyColor: '#d1fae5',
          text: '• 100% Client-side privacy\n• Lightning fast WebAssembly\n• No upload file size limits',
        },

        // Weaknesses
        {
          id: `swot_w_${now}`,
          type: 'rounded_rectangle',
          x: 550,
          y: 80,
          width: 440,
          height: 300,
          strokeColor: '#f59e0b',
          strokeWidth: 2,
          fillColor: 'rgba(245, 158, 11, 0.08)',
          opacity: 1,
          zIndex: 1,
        },
        {
          id: `swot_w_txt_${now}`,
          type: 'text',
          x: 575,
          y: 100,
          width: 200,
          height: 30,
          strokeColor: '#f59e0b',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 2,
          text: 'WEAKNESSES',
          fontSize: 18,
          bold: true,
        },
        {
          id: `swot_w_note_${now}`,
          type: 'sticky',
          x: 580,
          y: 150,
          width: 200,
          height: 120,
          strokeColor: '#f59e0b',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 3,
          stickyColor: '#fef3c7',
          text: '• High memory usage on 100+ page PDFs\n• Browser sandbox limitations',
        },

        // Opportunities
        {
          id: `swot_o_${now}`,
          type: 'rounded_rectangle',
          x: 80,
          y: 410,
          width: 440,
          height: 300,
          strokeColor: '#38bdf8',
          strokeWidth: 2,
          fillColor: 'rgba(56, 189, 248, 0.08)',
          opacity: 1,
          zIndex: 1,
        },
        {
          id: `swot_o_txt_${now}`,
          type: 'text',
          x: 105,
          y: 430,
          width: 200,
          height: 30,
          strokeColor: '#38bdf8',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 2,
          text: 'OPPORTUNITIES',
          fontSize: 18,
          bold: true,
        },
        {
          id: `swot_o_note_${now}`,
          type: 'sticky',
          x: 110,
          y: 480,
          width: 200,
          height: 120,
          strokeColor: '#38bdf8',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 3,
          stickyColor: '#e0f2fe',
          text: '• Realtime peer-to-peer WebRTC collaboration\n• Smart shape auto-beautifier',
        },

        // Threats
        {
          id: `swot_t_${now}`,
          type: 'rounded_rectangle',
          x: 550,
          y: 410,
          width: 440,
          height: 300,
          strokeColor: '#ec4899',
          strokeWidth: 2,
          fillColor: 'rgba(236, 72, 153, 0.08)',
          opacity: 1,
          zIndex: 1,
        },
        {
          id: `swot_t_txt_${now}`,
          type: 'text',
          x: 575,
          y: 430,
          width: 200,
          height: 30,
          strokeColor: '#ec4899',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 2,
          text: 'THREATS',
          fontSize: 18,
          bold: true,
        },
        {
          id: `swot_t_note_${now}`,
          type: 'sticky',
          x: 580,
          y: 480,
          width: 200,
          height: 120,
          strokeColor: '#ec4899',
          strokeWidth: 1,
          opacity: 1,
          zIndex: 3,
          stickyColor: '#fce7f3',
          text: '• Browser storage quotas clearing IndexedDB\n• Aggressive mobile RAM limits',
        },
      ];

      return {
        id: `board_${now}`,
        title: 'Strategic SWOT Analysis',
        createdAt: now,
        updatedAt: now,
        backgroundColor: '#0f172a',
        gridType: 'none',
        gridSnap: false,
        viewport: { x: 0, y: 0, zoom: 1 },
        elements,
        frames: [],
      };
    },
  },
];
